# Generated by Django 5.2.12 on 2026-03-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='system_permission', max_length=50)),
            ],
            options={
                'verbose_name': 'システム権限',
                'verbose_name_plural': 'システム権限',
                'permissions': [('can_view_system', 'システムを閲覧できる'), ('can_execute_system', '匿名化・DMZ送信・取込・取消を実施できる'), ('can_manage_users', 'ユーザーを管理できる'), ('can_manage_templates', 'プロンプトテンプレートを管理できる')],
            },
        ),
    ]
