# Generated by Django 5.2.12 on 2026-03-07 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(db_index=True, max_length=32)),
                ('prompt_filename', models.CharField(max_length=255)),
                ('result_filename', models.CharField(max_length=255)),
                ('saved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['request_no', 'saved_at'], name='open_app_op_request_8880ed_idx')],
            },
        ),
    ]
