# Generated by Django 5.2.12 on 2026-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_app', '0002_promptfileowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=255, unique=True)),
                ('has_error', models.BooleanField(default=False)),
                ('error_details', models.TextField(blank=True, default='')),
                ('check_score', models.IntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
